### PR TITLE
Updates for 2017 training

### PR DESCRIPTION
**Pull request by jgkamat**
Still a WIP, not even sure if it will build. Feel free to review it though

### CODE REVIEW

**Comment by jgkamat** [comment]
Build export is located here, untested currently: https://transfer.sh/IQnbA/robocup-5d876c60b8.zip

**Comment by jgkamat** [comment]
Made a small mistake when installing git hooks, fixing now.

**Comment by jgkamat** [comment]
New image is here: https://transfer.sh/lMR02/ubuntu1604-desktop-nocm-0.1.0.box. You can extract with tar.

Please let me know what you think, I think this is ready if no issues are found.

@joshhting @chachmu

**Comment by jgkamat** [comment]
Seems like the old link was too slow, so here's an alternate with the same file
https://mega.nz/#!g4dThaAD!_nZ0tnlKhDB8MaDB5iAR0DV-2ecPMJ0clpnOSt4_g0w

**Review by joshhting — APPROVED** [review]
This still requires users to run ubuntu-setup themselves to run the rrt-viewer, but other than that this image looks good to me.

**Comment by jgkamat** [comment]
The 'final' images are here. Please let me know immediately if you find issues with them:

https://transfer.sh/RrXGM/robocup-393ef97.zip

https://mega.nz/#!958GxYrB!CIVIHgDFbNXLgfjgxrVmWa8ZkVOvhaXRP_x48-dUO8s

Assuming @joshhting or @chachmu dosen't see any issues, @jpfeltracco these are the links that we need to send out.

**Pull request merged**
